import Anthropic from '@anthropic-ai/sdk';

const client = new Anthropic({
    baseURL: process.env.ANTHROPIC_BASE_URL || undefined,
  apiKey: process.env.ANTHROPIC_API_KEY,
});

export async function analyzeCompetitor(query: string) {
  if (!process.env.ANTHROPIC_API_KEY) {
    throw new Error('ANTHROPIC_API_KEY not configured');
  }

  const prompt = `You are a competitive analysis expert. Analyze the following competitor: "${query}"

Provide a comprehensive analysis with these sections:

## Company Overview
Brief description of what the company does, their target market, and business model.

## Key Strengths
3-5 bullet points highlighting their competitive advantages, unique features, or market position.

## Key Weaknesses
3-5 bullet points identifying potential vulnerabilities, limitations, or areas where they fall short.

## Market Position
Assessment of their standing in the market, including target audience, pricing strategy, and competitive differentiation.

## Recommendations
3-5 actionable recommendations for competing against this company, including specific strategies or features to consider.

Format your response as valid JSON matching this structure:
{
  "overview": "string",
  "strengths": ["string", "string", "string"],
  "weaknesses": ["string", "string", "string"],
  "marketPosition": "string",
  "recommendations": ["string", "string", "string"]
}

Return ONLY the JSON object, no additional text.`;

  const message = await client.messages.create({
    model: 'claude-sonnet-4-5-20250929',
    max_tokens: 2000,
    messages: [
      {
        role: 'user',
        content: prompt,
      },
    ],
  });

  const content = message.content[0];
  if (content.type !== 'text') {
    throw new Error('Unexpected response type from Anthropic API');
  }

  // Extract JSON from response
  const jsonMatch = content.text.match(/\{[\s\S]*\}/);
  if (!jsonMatch) {
    throw new Error('Failed to extract JSON from response');
  }

  const analysis = JSON.parse(jsonMatch[0]);
  return {
    analysis,
    markdown: generateMarkdownReport(query, analysis),
  };
}

function generateMarkdownReport(query: string, analysis: any): string {
  return `# Competitive Analysis: ${query}

## Company Overview
${analysis.overview}

## Key Strengths
${analysis.strengths.map((s: string) => `- ${s}`).join('\n')}

## Key Weaknesses
${analysis.weaknesses.map((w: string) => `- ${w}`).join('\n')}

## Market Position
${analysis.marketPosition}

## Recommendations
${analysis.recommendations.map((r: string) => `- ${r}`).join('\n')}

---
*Generated by Competitor Quick Scan*`;
}